name: Build and Upload Artifact

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build with Maven
      run: mvn -B clean package

    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-zip
        path: target/*.zip
